### PR TITLE
Allow to disable tmux

### PR DESCRIPTION
**Pull request by felipecrs**
# Proposed Changes

I can't express how much I hate interacting with tmux. It brings me zero benefits and yet a lot of pain.

To say the least, it completely breaks the experience when using Android to interact with the terminal Web UI.

This adds a new option to allow disabling tmux.

## Related Issues

None.

### CODE REVIEW

**Comment by frenck** [comment]
Sorry, I have no interest in adding this option.

Thanks for being willing to contribute.

../Frenck

**Comment by felipecrs** [comment]
Sorry... I know you own the add-on, but having an option like this brings no problem, does it?

Try accessing the terminal Web UI from your Home Assistant Companion app, and try to copy and paste some text, for example. You will see that it is barely possible.

Can I ask why you prefer not to have this option?

**Comment by frenck** [comment]
Because having many options isn't a good thing.

There are init commands available if you want customization.

**Comment by felipecrs** [comment]
> This request hasn't popped up even once

Probably because most people don't even know what tmux is, and that this add-on uses it, and that it is the culprit for the issues I mentioned.

Maybe because people tried to use the add-on Web UI in Android, it did not work, they gave up and never reported as well.

But if you REALLY want to hide it:

- I can make it an optional option so that it won't appear in the list by default
- I can check for the presence of a file named `/tmp/do-not-use-tmux` in `ttyd/run`, which would NOT be documented, and to disable tmux, users need to add `touch /tmp/do-not-use-tmux` to their init commands.

What do you think?

> There are init commands available if you want customization.

I tried to use it to disable tmux, but it is apparently not possible. Things I tried:

```
sed --in-place 's/tmux -u new -A -s homeassistant //g' /run/s6/db/servicedirs/ttyd/run /etc/s6-overlay/s6-rc.d/ttyd/run /run/s6-rc:s6-rc-init:*/servicedirs/ttyd/run
```

The files gets edited correctly (I can confirm after starting the add-on), but s6 does not seem to pick the changes up. I believe s6 computes the services into memory after the first initialization and it won't matter trying to change them after.

**Comment by frenck** [comment]
That is still providing the option I just declined.

**Comment by felipecrs** [comment]
If you would like me to change this PR, let me know.

Otherwise, can you please suggest an approach to disable tmux?

(other than forking, building and pushing the add-on myself)

**Pull request closed without merging**
