### PR TITLE
Change default shell from /bin/ash to /bin/sh

### PR DESCRIPTION
**Pull request by rskallies**
# Proposed Changes

Change default shell from /bin/ash to /bin/sh

## Related Issues

#744 

## Summary by CodeRabbit

- **Chores**
  - Updated the SSH Dockerfile to use `zsh` instead of `sh` for the default shell environment. This change affects the shell experience by providing enhanced features and a more user-friendly interface.

### CODE REVIEW

**Comment by dfries** [comment]
I'm seeing /etc/passwd
`root:x:0:0:root:/root:/bin/sh`
so I can see why `sed -i -e "s#bin/ash#bin/zsh#" /etc/passwd` would fail.
Please make the shell configurable.  I see bash is installed and that's my preference.
zsh prompt on the other hand takes much longer to startup and the prompt outputs unprintable garbage at the start.

**Comment by frenck** [comment]
> Please make the shell configurable. I see bash is installed and that's my preference.

That is already configurable, please read some documentation, that is my preference 😛

**Comment by frenck** [comment]
This PR fails, caused by the base image to be behind. I'm trying to debug why Renovate didn't make an update / PR to bump the dependency (that has been available for two weeks at this point).

../Frenck

**Comment by dfries** [comment]
> please read some documentation, that is my preference

"Option: zsh ... By setting this option to false, you will disable ZSH and the add-on will fallback to Bash instead."

I have it disabled and I don't get bash.

Okay, so the existing Dockerfile `sed -i -e "s#bin/ash#bin/zsh#" /etc/passwd` is failing to update /etc/passwd to zsh and ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run then is failing to update it to bash.

I've cloned this repository and am trying to install it.  Generic question "Failed to install add-on" gives me "returned a non-zero code: 19" that's not much to go by.  I have Home Assistant Operating System installed to a RPI 3, is there a way to get more information to debug when Dockerfile RUN fails?  I have your latest changes commit d5a8c9ce3 "Docker tag to v16.0.1" it hasn't failed yet, but any tips on how to debug when building a container fails in the future installing add-ons in Home Assistant OS?

**Comment by frenck** [comment]
You are kinda out of scope for this Pr. Let's keep PR to reviews please. Thanks 🙏

**Review by frenck — COMMENTED** [review]
Thanks @rskallies 👍 

Will ship in the morning (got an Alpine Linux update ln route as well).

../Frenck

**Review by frenck — APPROVED** [review]

**Comment by dfries** [comment]
Back to this pull request then.

I'm thinking it was /bin/ash it is /bin/sh what if it were changed to /bin/dash in the future?  Could check for bin/.*sh
```
&& sed -i -e "s#bin/.*sh#bin/zsh#" /etc/passwd \
```

Could completely ignore the shell, but this assumes only root will ever need updating.
```
sed -i -e 's#^\(root.*:\)/bin.*#\1/bin/zsh#' /etc/passwd \
```

**Pull request merged**
