### PR TITLE
Document using other shells, add small recipe for bash

### PR DESCRIPTION
**Pull request by scop**
# Proposed Changes

> (Describe the changes and rationale behind them)

zsh might be a bit too much/different for users of other shells. Add a note in the doc how one can go about changing it, and provide a small example for bash.

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

https://github.com/hassio-addons/addon-ssh/issues/27

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by scop** [comment]
I suggest applying #109 first, otherwise a command that takes care of HASSIO_TOKEN for bash should be added to the example.

**Comment by frenck** [comment]
The order of merging for the community add-ons do not matter as much (compared to the core add-ons).

Merging will no result in release. The community add-ons use git tags to actually mark a release. Merge commits are built, but only end up on the edge repository (containing dev builds).

I might not merge this, mainly because I have a different idea I'm exploring right now.

**Comment by frenck** [comment]
I've added native support for changing to Bash in the upcoming release.

Implemented in <https://github.com/hassio-addons/addon-ssh/commit/61e8e17933bbc4d04e6f35eabb8d8becf1e6401c>

Bash completion support added in: https://github.com/hassio-addons/addon-ssh/commit/6f0ec3a5ed39abc85c9a95242ec2886284ad262c

**Comment by frenck** [comment]
Closing this PR, since it is not needed in that case :)

Thanks for pushing me towards this! 👍

**Pull request closed without merging**
